options:
  docker: true
  size: 2x

pipelines:
  tags:
    release-*:
      - step:
          name: Build Latest Release
          image: atlassian/default-image:2
          caches:
            - docker
          services:
            - docker
          size: 2x 
          script:
             # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
            - export IMAGE_NAME=workwise/frontend:latest
            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker build -f Dockerfile.production -t $IMAGE_NAME .
            # authenticate with the Docker Hub registry
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # push the new Docker image to the Docker registry
            - docker push $IMAGE_NAME
  branches:
    master:
      - step:
          name: Build Master (Stable)
          image: atlassian/default-image:2
          caches:
            - docker
          services:
            - docker
          size: 2x 
          script:
             # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
            - export IMAGE_NAME=workwise/frontend:master
            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker build  -f Dockerfile.production -t $IMAGE_NAME .
            # authenticate with the Docker Hub registry
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # push the new Docker image to the Docker registry
            - docker push $IMAGE_NAME
    develop:
      - step:
          name: Build Develop (Unstable)
          image: atlassian/default-image:2
          caches:
            - docker
          services:
            - docker
          size: 2x 
          script:
             # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
            - export IMAGE_NAME=workwise/frontend:develop
            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker build -f Dockerfile.production  -t $IMAGE_NAME .
            # authenticate with the Docker Hub registry
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # push the new Docker image to the Docker registry
            - docker push $IMAGE_NAME
    feature/*:
      - step:
          name: Build Feature Branch (Node Only)
          image: node:12.19.0
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            - npm install react-scripts@3.4.3 -g
            - CI=false npm run-script build
definitions:
  services:
    docker:
      memory: 4096
